// GENERATED by scripts/generate-cards.mts — do not edit by hand.
// Maps a game slug to its card image filename under public/game-cards/.

export const cardArt: Record<string, string> = {
  "helicopter": "helicopter.jpg",
};
