/**
 * Generates game card art via the xAI image API.
 *
 * This is a local, on-demand tool — it is not part of the build and the API
 * key never needs to reach Vercel. Output lands in public/game-cards/ and is
 * committed alongside a generated manifest (lib/cardArt.ts) so the running
 * app needs no network access.
 *
 *   node scripts/generate-cards.mts --dry-run          # print prompts, call nothing
 *   node scripts/generate-cards.mts --only snake,pong  # generate specific games
 *   node scripts/generate-cards.mts                    # generate everything missing
 *   node scripts/generate-cards.mts --force            # regenerate even if present
 *
 * Existing art is skipped unless --force, so a partial run is safe to resume
 * and re-running after a failure costs nothing for images already made.
 */
import { writeFile, mkdir, readdir } from "node:fs/promises";
import path from "node:path";
import { games, type Game } from "../lib/games.ts";

const OUT_DIR = path.join(process.cwd(), "public", "game-cards");
const MANIFEST = path.join(process.cwd(), "lib", "cardArt.ts");
const ENDPOINT = "https://api.x.ai/v1/images/generations";
const MODEL = "grok-imagine-image-quality";

/**
 * Pinning the style hard is the whole game here. Fifty independently generated
 * images drift wildly unless every prompt ends with the same art direction, so
 * this suffix is deliberately specific about medium, palette, lighting, and
 * framing — and explicitly bans text, which image models love to add and
 * always render as garbled pseudo-letters.
 */
const STYLE = [
  "16-bit pixel art game cover illustration",
  "retro arcade cabinet art style",
  "warm dark background (deep brown #1a0e0a) with vivid neon accent lighting",
  "bold silhouette, high contrast, strong rim light",
  "centered single subject, cinematic wide composition",
  "clean readable shapes, no clutter",
  "absolutely no text, no words, no letters, no numbers, no logos, no watermarks, no UI",
].join(", ");

type Args = {
  dryRun: boolean;
  force: boolean;
  only: string[] | null;
};

function parseArgs(argv: string[]): Args {
  const only = argv.find((a) => a.startsWith("--only="))?.split("=")[1]
    ?? (argv.includes("--only") ? argv[argv.indexOf("--only") + 1] : undefined);
  return {
    dryRun: argv.includes("--dry-run"),
    force: argv.includes("--force"),
    only: only ? only.split(",").map((s) => s.trim()).filter(Boolean) : null,
  };
}

function promptFor(game: Game): string {
  return `${game.title} — ${game.blurb} ${game.description.slice(0, 220)}. Accent color ${game.accent}. ${STYLE}`;
}

async function existingSlugs(): Promise<Set<string>> {
  try {
    const files = await readdir(OUT_DIR);
    return new Set(files.map((f) => path.parse(f).name));
  } catch {
    return new Set();
  }
}

async function generate(game: Game, apiKey: string): Promise<Buffer> {
  const res = await fetch(ENDPOINT, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model: MODEL,
      prompt: promptFor(game),
      n: 1,
      aspect_ratio: "16:9", // matches the tile's aspect-video frame
      response_format: "b64_json",
    }),
  });

  if (!res.ok) {
    throw new Error(`xAI ${res.status}: ${(await res.text()).slice(0, 400)}`);
  }

  const body = (await res.json()) as {
    data?: { b64_json?: string; url?: string }[];
  };
  const item = body.data?.[0];
  if (!item) throw new Error("xAI returned no image data");

  if (item.b64_json) return Buffer.from(item.b64_json, "base64");
  if (item.url) {
    const img = await fetch(item.url);
    if (!img.ok) throw new Error(`image fetch ${img.status}`);
    return Buffer.from(await img.arrayBuffer());
  }
  throw new Error("xAI response had neither b64_json nor url");
}

async function writeManifest(): Promise<number> {
  const files = (await readdir(OUT_DIR)).filter((f) => !f.startsWith("."));
  const bySlug = new Map<string, string>();
  for (const f of files) bySlug.set(path.parse(f).name, f);

  const entries = games
    .filter((g) => bySlug.has(g.slug))
    .map((g) => `  ${JSON.stringify(g.slug)}: ${JSON.stringify(bySlug.get(g.slug)!)},`)
    .join("\n");

  const src = `// GENERATED by scripts/generate-cards.mts — do not edit by hand.
// Maps a game slug to its card image filename under public/game-cards/.

export const cardArt: Record<string, string> = {
${entries}
};
`;
  await writeFile(MANIFEST, src, "utf8");
  return games.filter((g) => bySlug.has(g.slug)).length;
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const apiKey = process.env.XAI_API_KEY?.trim();

  await mkdir(OUT_DIR, { recursive: true });
  const have = await existingSlugs();

  let targets = games;
  if (args.only) {
    const known = new Set(games.map((g) => g.slug));
    const unknown = args.only.filter((s) => !known.has(s));
    if (unknown.length) {
      console.error(`Unknown slug(s): ${unknown.join(", ")}`);
      process.exit(1);
    }
    targets = games.filter((g) => args.only!.includes(g.slug));
  }
  if (!args.force) {
    targets = targets.filter((g) => !have.has(g.slug));
  }

  if (args.dryRun) {
    console.log(`DRY RUN — ${targets.length} game(s) would be generated:\n`);
    for (const g of targets) console.log(`── ${g.slug}\n${promptFor(g)}\n`);
    console.log(`No API calls made. ${have.size} game(s) already have art.`);
    return;
  }

  if (!apiKey) {
    console.error("XAI_API_KEY is not set. Add it to .env.local or export it.");
    process.exit(1);
  }
  if (targets.length === 0) {
    console.log("Nothing to generate — all targeted games already have art.");
    await writeManifest();
    return;
  }

  console.log(`Generating ${targets.length} card(s)…`);
  let ok = 0;
  const failed: string[] = [];

  // Sequential on purpose: keeps well clear of rate limits and makes a
  // mid-run failure cheap to resume, since finished images are skipped.
  for (const [i, game] of targets.entries()) {
    process.stdout.write(`[${i + 1}/${targets.length}] ${game.slug} … `);
    try {
      const buf = await generate(game, apiKey);
      await writeFile(path.join(OUT_DIR, `${game.slug}.jpg`), buf);
      console.log(`ok (${Math.round(buf.length / 1024)} KB)`);
      ok++;
    } catch (err) {
      console.log(`FAILED — ${(err as Error).message}`);
      failed.push(game.slug);
    }
  }

  const total = await writeManifest();
  console.log(`\n${ok} generated, ${failed.length} failed. Manifest lists ${total} game(s).`);
  if (failed.length) {
    console.log(`Retry just those:\n  node scripts/generate-cards.mts --only ${failed.join(",")}`);
    process.exitCode = 1;
  }
}

await main();
